version: '2'
services:
    gui:
        image: microcoffee-gui:1.0.0-SNAPSHOT
        ports:
            - "8080:8080"
            - "8443:8443"
        links:
            - location
            - order
    location:
        image: microcoffee-location:1.0.0-SNAPSHOT
        ports:
            - "8081:8081"
            - "8444:8444"
        links:
            - mongodb
    order:
        image: microcoffee-order:1.0.0-SNAPSHOT
        ports:
            - "8082:8082"
            - "8445:8445"
        links:
            - mongodb
    mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes:
            - mongodbdata:/data/db
volumes:
    mongodbdata:
        external: true
