version: '2'
services:
    location:
        image: microcoffee-location:1.0.0-SNAPSHOT
        ports:
            - "8081:8081"
            - "8444:8444"
        links:
            - mongodb
    mongodb:
        image: mongo:3.4.8
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes:
            - mongodbdata:/data/db
volumes:
    mongodbdata:
        external: true
