version: '2'
services:
    order:
        image: microcoffee-order:1.0.0-SNAPSHOT
        ports:
            - "8082:8082"
        links:
            - mongodb
    mongodb:
        image: tutum/mongodb:3.2
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes:
            - mongodbdata:/data/db
        environment:
            - AUTH=no
volumes:
    mongodbdata:
        external: true
